project:
  type: website
  output-dir: _site

website:
  title: "AmericanTalksFooty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: FCC Reports
        href: reports.qmd
      - text: Random
        href: random.qmd

format:
  html:
    theme: lumen
    css: styles.css