project:
  type: website
  output-dir: docs

website:
  title: "FC Cincinnati Match Reports"
  site-url: "https://ethanheck.github.io/FCCreport"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reports.qmd
        text: Reports
      - href: about.qmd
        text: About

format:
  html:
    theme: darkly
    css: styles.css  # Loads the custom CSS file
    toc: true