project:
  type: website
  output-dir: docs  # Ensures GitHub Pages serves from /docs

website:
  title: "FC Cincinnati Match Reports"
  site-url: "https://ethanheck.github.io/FCCreport" # Update with your GitHub Pages URL
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reports.qmd
        text: Reports
      - href: about.qmd
        text: About

format:
  html:
    theme: darkly    # Other themes: journal, flatly, yeti
    toc: true