project:
  type: website
  output-dir: docs
  resources:
    - "images/*"

website:
  title: "FC Cincinnati Match Reports"
  site-url: "https://ethanheck.github.io/FCCreport"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: reports.qmd
        text: Reports
      - href: about.qmd
        text: About
    search: false  # This removes the search button

format:
  html:
    theme: darkly
    css: styles.css
    toc: true