project:
  type: website
  output-dir: _site

website:
  title: "Ethan's Analysis Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reports.qmd
        text: Reports
      - href: random.qmd
        text: Random
      - href: reports/intro.html
        text: About

format:
  html:
    theme: lumen
    css: styles.css